### ISSUE TITLE
Failed to open database 

### ISSUE THREAD

**Issue by ModirGithub** [rorist/android-network-discovery#30]
at info.lamatricexiste.network.Network.HardwareAddress.getNicVendor(HardwareAddress.java:82)
        at info.lamatricexiste.network.DefaultDiscovery.publish(DefaultDiscovery.java:263)
        at info.lamatricexiste.network.DefaultDiscovery.access$000(DefaultDiscovery.java:30)
        at info.lamatricexiste.network.DefaultDiscovery$CheckRunnable.run(DefaultDiscovery.java:184)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
2022-07-31 11:19:57.917 11115-11322/? E/HardwareAddress: unknown error (code 14): Could not open database
2022-07-31 11:19:57.917 11115-11319/? E/SQLiteDatabase: Failed to open database '/data/data/info.lamatricexiste.network/files/saves.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database

**Comment by clover696** [comment]
How?
